// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	fiber "github.com/gofiber/fiber/v2"
	mock "github.com/stretchr/testify/mock"
)

// UserHandler is an autogenerated mock type for the UserHandler type
type UserHandler struct {
	mock.Mock
}

type UserHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *UserHandler) EXPECT() *UserHandler_Expecter {
	return &UserHandler_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx
func (_m *UserHandler) Delete(ctx *fiber.Ctx) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx *fiber.Ctx
func (_e *UserHandler_Expecter) Delete(ctx interface{}) *UserHandler_Delete_Call {
	return &UserHandler_Delete_Call{Call: _e.mock.On("Delete", ctx)}
}

func (_c *UserHandler_Delete_Call) Run(run func(ctx *fiber.Ctx)) *UserHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *UserHandler_Delete_Call) Return(_a0 error) *UserHandler_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserHandler_Delete_Call) RunAndReturn(run func(*fiber.Ctx) error) *UserHandler_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *UserHandler) GetAll(ctx *fiber.Ctx) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserHandler_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type UserHandler_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx *fiber.Ctx
func (_e *UserHandler_Expecter) GetAll(ctx interface{}) *UserHandler_GetAll_Call {
	return &UserHandler_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *UserHandler_GetAll_Call) Run(run func(ctx *fiber.Ctx)) *UserHandler_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *UserHandler_GetAll_Call) Return(_a0 error) *UserHandler_GetAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserHandler_GetAll_Call) RunAndReturn(run func(*fiber.Ctx) error) *UserHandler_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx
func (_m *UserHandler) GetByID(ctx *fiber.Ctx) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserHandler_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserHandler_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx *fiber.Ctx
func (_e *UserHandler_Expecter) GetByID(ctx interface{}) *UserHandler_GetByID_Call {
	return &UserHandler_GetByID_Call{Call: _e.mock.On("GetByID", ctx)}
}

func (_c *UserHandler_GetByID_Call) Run(run func(ctx *fiber.Ctx)) *UserHandler_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *UserHandler_GetByID_Call) Return(_a0 error) *UserHandler_GetByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserHandler_GetByID_Call) RunAndReturn(run func(*fiber.Ctx) error) *UserHandler_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrent provides a mock function with given fields: ctx
func (_m *UserHandler) GetCurrent(ctx *fiber.Ctx) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserHandler_GetCurrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrent'
type UserHandler_GetCurrent_Call struct {
	*mock.Call
}

// GetCurrent is a helper method to define mock.On call
//   - ctx *fiber.Ctx
func (_e *UserHandler_Expecter) GetCurrent(ctx interface{}) *UserHandler_GetCurrent_Call {
	return &UserHandler_GetCurrent_Call{Call: _e.mock.On("GetCurrent", ctx)}
}

func (_c *UserHandler_GetCurrent_Call) Run(run func(ctx *fiber.Ctx)) *UserHandler_GetCurrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *UserHandler_GetCurrent_Call) Return(_a0 error) *UserHandler_GetCurrent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserHandler_GetCurrent_Call) RunAndReturn(run func(*fiber.Ctx) error) *UserHandler_GetCurrent_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx
func (_m *UserHandler) Login(ctx *fiber.Ctx) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserHandler_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type UserHandler_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx *fiber.Ctx
func (_e *UserHandler_Expecter) Login(ctx interface{}) *UserHandler_Login_Call {
	return &UserHandler_Login_Call{Call: _e.mock.On("Login", ctx)}
}

func (_c *UserHandler_Login_Call) Run(run func(ctx *fiber.Ctx)) *UserHandler_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *UserHandler_Login_Call) Return(_a0 error) *UserHandler_Login_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserHandler_Login_Call) RunAndReturn(run func(*fiber.Ctx) error) *UserHandler_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx
func (_m *UserHandler) Logout(ctx *fiber.Ctx) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserHandler_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type UserHandler_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx *fiber.Ctx
func (_e *UserHandler_Expecter) Logout(ctx interface{}) *UserHandler_Logout_Call {
	return &UserHandler_Logout_Call{Call: _e.mock.On("Logout", ctx)}
}

func (_c *UserHandler_Logout_Call) Run(run func(ctx *fiber.Ctx)) *UserHandler_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *UserHandler_Logout_Call) Return(_a0 error) *UserHandler_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserHandler_Logout_Call) RunAndReturn(run func(*fiber.Ctx) error) *UserHandler_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx
func (_m *UserHandler) Register(ctx *fiber.Ctx) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserHandler_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type UserHandler_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx *fiber.Ctx
func (_e *UserHandler_Expecter) Register(ctx interface{}) *UserHandler_Register_Call {
	return &UserHandler_Register_Call{Call: _e.mock.On("Register", ctx)}
}

func (_c *UserHandler_Register_Call) Run(run func(ctx *fiber.Ctx)) *UserHandler_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *UserHandler_Register_Call) Return(_a0 error) *UserHandler_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserHandler_Register_Call) RunAndReturn(run func(*fiber.Ctx) error) *UserHandler_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx
func (_m *UserHandler) Update(ctx *fiber.Ctx) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx *fiber.Ctx
func (_e *UserHandler_Expecter) Update(ctx interface{}) *UserHandler_Update_Call {
	return &UserHandler_Update_Call{Call: _e.mock.On("Update", ctx)}
}

func (_c *UserHandler_Update_Call) Run(run func(ctx *fiber.Ctx)) *UserHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *UserHandler_Update_Call) Return(_a0 error) *UserHandler_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserHandler_Update_Call) RunAndReturn(run func(*fiber.Ctx) error) *UserHandler_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserHandler creates a new instance of UserHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserHandler {
	mock := &UserHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
